### ISSUE TITLE
TF-Movidius-Finetune Inception Model

### ISSUE THREAD

**Issue by AziziShekoofeh** [Technica-Corporation/TF-Movidius-Finetune#1]
Hi,

Thanks for the really nice package.  It's really helpful. During using the package I've encounter two issues:

1- When I am trying to generate the records for a large number of classes and samples, It generates the records without any errors, but when I am using the records in train.py code I am getting the error that:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: image_size must contain 3 elements[4]
         [[Node: distort_image/distorted_bounding_box_crop/SampleDistortedBoundingBox = SampleDistortedBoundingBox[T=DT_INT32, area_range=[0.05, 1], aspect_ratio_range=[0.75, 1.33], max_attempts=100, min_object_covered=0.1, seed=0, seed2=0, use_image_if_no_bounding_boxes=true, _device="/job:localhost/replica:0/task:0/cpu:0"](distort_image/distorted_bounding_box_crop/Shape/_1287, distort_image/Const)]]
```
The train and export to device readable graph are works fine with a small subset of the dataset that I have. 
My dataset includes png and jpeg images. 

2- The other issue is with evaluation code which I couldn't get any answer from:

```

InvalidArgumentError (see above for traceback): targets[0] is out of range
         [[Node: in_top_k/InTopKV2 = InTopKV2[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](MobilenetV1/Logits/SpatialSqueeze/_965, Reshape_3/_967, in_top_k/InTopKV2/k)]]
         [[Node: in_top_k/InTopKV2/_969 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_376_in_top_k/InTopKV2", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```

Do you ever face similar problem? It would be great if you can share your experience with me. 

I also have two question:

1- Have you ever tried to use these codes with InceptionV3? What are the possible changes to the code?
2- Also, how we can change the code to run on CPU, It seems it has been written for GPU version only.

Many thanks. - Shek

**Comment by adl2db** [comment]
Hi Shek, 

In general it seems like the issue lays in the conversion of the images to TFRecord format so I would start looking in there to make sure the create_tfrecord.py tool is being used correctly 
1. Without knowing too much about the data, it's difficult to tell. Seems the error is being raised in the Inception preprocessing module - seems like the TFRecord image data being decoded has less than 3 dimensions (expecting height, width, channels)
2. Here the issue appears to be that the labels are never generated when creating the TFRecord file. I suspect that there's a mismatch between the image directory structure. The create_tfrecord tool expects the file structure to be where each subfolder is the set of images related to that label. For example in the often used flowers dataset, it would expect a main folder called 'flowers' where subfolders are organized by label containing images of each class (e.g. flowers/daisy/1.jpg, flowers/dandelion/1.jpg, etc.)


Haven't really encountered any of your problems myself, and this is with running . Could probably have done a better job explaining the conversion process.

1. We've tested the InceptionV3 model, using the --model_name flag to specify inception_v3 which seems to work well.
2. Running on CPU can be easily done by setting your environment variable CUDA_VISIBLE_DEVICES, like so:
`export CUDA_VISIBLE_DEVICES=''`

**Comment by AziziShekoofeh** [comment]
@adl2db Thank you so much for the response. I will check them out again and let you know if I had any progress. Many thanks.

**Comment by AziziShekoofeh** [comment]
Hi,

I still do have the problem with tf records. It's a bit mysterious, I could say definitely it is coming from the format of a few images, I did remove every other format than jpeg, but it is still an error about the dimension: 

```
e 4-dimensional[1,1,323,289,3]
         [[Node: ResizeNearestNeighbor = ResizeNearestNeighbor[T=DT_UINT8, align_corners=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims, distort_image/size)]]

```

Could you please let me know, which input argument have to change to get the results for InceptionV3:
1- I did change the --model_name to inception_v3
2- I am not sure if there is a need to change --checkpoint_exclude_scopes  and if it's needed which scopes should be exclude.
3- and Also, I changed the checkpoint and feed it with the inception_v3.ckpt 


Many thanks, -Shek

**Comment by adl2db** [comment]
You always need to have --checkpoint_exclude_scopes flag set when loading from a pre-trained ImageNet checkpoint. This is so you do not define the 1001 class final layer from the checkpoint, for inceptionV3 use like so
`--checkpoint_exclude_scopes='InceptionV3/Logits, InceptionV3/AuxLogits`
if you're looking to only train the last layer (e.g. transfer learning) then also use this flag
`--trainable_scopes='InceptionV3/Logits,InceptionV3/AuxLogits`

From the limited msg, it seems as if the data has been formatted to 5-dimensional, where it should be 4-dimensional [batch_size, W, H, C] or better known as NWHC format.

**Comment by AziziShekoofeh** [comment]
@adl2db Thank you so much for all your help.

**Comment by iandow** [comment]
The README says graph files from retrain.py in the tensorflow-for-poets won't work. I'm trying to troubleshoot that.  Is this the error you're getting?

```
Traceback (most recent call last):
  File "./run.py", line 47, in <module>
    graph = device.AllocateGraph(graphfile)
  File "/usr/local/lib/python3.5/dist-packages/mvnc/mvncapi.py", line 203, in AllocateGraph
    raise Exception(Status(status))
Exception: mvncStatus.UNSUPPORTED_GRAPH_FILE
```

**Comment by SomeUserName1** [comment]
I am using MNIST data from kaggle. It successfully converted data to tfrecords but I am not able to locate checkpoint file. I am getting following error:
`tensorflow.python.framework.errors_impl.NotFoundError: ./models/checkpoints; No such file or directory`
Can you please direct me which path it should be in?

**Comment by aarti-b** [comment]
I am using MNIST data from kaggle, I successfully converted data to tfrecords. But I am unable to locate checkpoint file. I am getting the following error.
`tensorflow.python.framework.errors_impl.NotFoundError: ./models/checkpoints; No such file or directory`  Where is it located?
